const myName = "Ali Yahya";

const accountRepo = 50 ;

console.log (myName + "" +  accountRepo)

console.log ( `my name is ${myName} and my github repo is ${accountRepo}`)


const newName = "AliYaha"

const yourName = new String("AliYahya")

console.log (yourName.charAt(3))
console.log (yourName.indexOf('i'))

let anotherString = yourName.slice(0,8)

console.log(anotherString)

console.log(yourName.substring (0,8));
console.log (yourName.slice(0,4))


// let userName = "Ali_Yah_ya"

console.log(userName);
console.log(userName.trim());

let userLink = "https//:facebok.com/%34mfmr.aliyah"

console.log (userLink.replace('%34' , '__'))

console.log (userLink.include('facebok.com'));
let userName = "Ali_Yah_ya"
let position = userName.split();

console.log (position)


